# The following variables define reusable configurations for deployment, providing consistent and predefined
# behaviors for updating, rolling back, and restarting services.

x-deploy-default: &deploy-default
  update_config:
    failure_action: rollback
    parallelism: 1
    delay: 10s
  rollback_config:
    parallelism: 1
    delay: 10s
  restart_policy:
    window: 360s
    delay: 30s
    # Max 24hours
    max_attempts: 240

x-default: &default
  networks:
    - mna_network

services:
  server:
    <<: *default
    image: ghcr.io/mission-apprentissage/mna_{{product_name}}_server:{{app_version}}
    deploy:
      <<: *deploy-default
      resources:
        limits:
          memory: 2g
      replicas: 2
    env_file: .env_server
    stop_grace_period: 60s
    volumes:
      - /opt/app/data/server:/data
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.json.{{product_name}}.{{env_type}}.server
        fluentd-async: "true"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/api/healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 11
      start_period: 10s

  ui:
    <<: *default
    image: ghcr.io/mission-apprentissage/mna_{{product_name}}_ui:{{app_version}}-{{env_type}}
    deploy:
      <<: *deploy-default
      resources:
        limits:
          memory: 256m
      replicas: 2
    env_file: .env_ui
    stop_grace_period: 60s
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.txt.{{product_name}}.{{env_type}}.ui
        fluentd-async: "true"
